<a href="https://colab.research.google.com/github/JamesLeeeeeee/torchbase/blob/master/torchbase_20220117.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
w= torch.tensor(2.0, requires_grad=True)

In [5]:
y= w**2
z=2*y+5

In [8]:
z.backward()

In [10]:
print('수식을 w로 미분한 값 : {}'.format(w.grad))

수식을 w로 미분한 값 : 8.0


In [11]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
torch.manual_seed(1)

In [12]:
x1_train= torch.FloatTensor([[73],[93],[89],[96],[73]])
x2_train= torch.FloatTensor([[80],[88],[91],[98],[66]])
x3_train= torch.FloatTensor([[75],[93],[90],[100],[70]])
y_train= torch.FloatTensor([[152],[185],[180],[196],[142]])

In [13]:
w1=torch.zeros(1,requires_grad=True)
w2=torch.zeros(1,requires_grad=True)
w3=torch.zeros(1,requires_grad=True)
b=torch.zeros(1,requires_grad=True)

In [17]:
optimizer= optim.SGD([w1,w2,w3,b], lr=1e-5)
nb_epochs=1000
for epoch in range(nb_epochs+1):
  hypothesis= x1_train*w1+x2_train*w2+x3_train*w3+b

  cost= torch.mean((hypothesis-y_train)**2)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch%100==0:
    print('Epoch {:4d}/{} w1:{:.3f} w2:{:.3f} w3:{:.3f} b: {:.3f} Cost:{:.6f}'.format(
        epoch, nb_epochs, w1.item(), w2.item(), w3.item(), b.item(), cost.item()
    ))

Epoch    0/1000 w1:0.718 w2:0.612 w3:0.680 b: 0.009 Cost:1.078964
Epoch  100/1000 w1:0.722 w2:0.608 w3:0.680 b: 0.009 Cost:1.038180
Epoch  200/1000 w1:0.727 w2:0.603 w3:0.681 b: 0.010 Cost:0.999513
Epoch  300/1000 w1:0.731 w2:0.599 w3:0.681 b: 0.010 Cost:0.962859
Epoch  400/1000 w1:0.735 w2:0.595 w3:0.681 b: 0.010 Cost:0.928092
Epoch  500/1000 w1:0.739 w2:0.590 w3:0.681 b: 0.010 Cost:0.895123
Epoch  600/1000 w1:0.743 w2:0.586 w3:0.682 b: 0.010 Cost:0.863870
Epoch  700/1000 w1:0.746 w2:0.582 w3:0.682 b: 0.010 Cost:0.834221
Epoch  800/1000 w1:0.750 w2:0.579 w3:0.682 b: 0.010 Cost:0.806112
Epoch  900/1000 w1:0.754 w2:0.575 w3:0.682 b: 0.010 Cost:0.779432
Epoch 1000/1000 w1:0.757 w2:0.571 w3:0.682 b: 0.011 Cost:0.754143


In [19]:
x_train= torch.FloatTensor([[73,80,75],
                           [93,88,93],
                           [89,91,80],
                           [96,98,100],
                           [73,66,70]])
y_train= torch.FloatTensor([[152],[185],[180],[196],[142]])

In [20]:
print(x_train.shape)
print(y_train.shape)

torch.Size([5, 3])
torch.Size([5, 1])


In [21]:
W= torch.zeros((3,1),requires_grad=True)
b= torch.zeros(1, requires_grad=True)

In [22]:
hypothesis= x_train.matmul(W)+b

In [24]:
optimizer= optim.SGD([W,b], lr=1e-5)
nb_epochs=20
for epoch in range(nb_epochs+1):

  hypothesis= x_train.matmul(W)+b

  cost=torch.mean((hypothesis-y_train)**2)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  print('Epoch:{:4d}/ {} hypothesis: {} Cost: {:.6f}'.format(epoch, nb_epochs,
                                                             hypothesis.squeeze().detach(),
                                                             cost.item())
  )

Epoch:   0/ 20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch:   1/ 20 hypothesis: tensor([66.7178, 80.1701, 76.1025, 86.0194, 61.1565]) Cost: 9537.694336
Epoch:   2/ 20 hypothesis: tensor([104.5421, 125.6208, 119.2478, 134.7862,  95.8280]) Cost: 3069.590088
Epoch:   3/ 20 hypothesis: tensor([125.9858, 151.3882, 143.7087, 162.4333, 115.4844]) Cost: 990.670288
Epoch:   4/ 20 hypothesis: tensor([138.1429, 165.9963, 157.5768, 178.1071, 126.6283]) Cost: 322.481873
Epoch:   5/ 20 hypothesis: tensor([145.0350, 174.2780, 165.4395, 186.9928, 132.9461]) Cost: 107.717064
Epoch:   6/ 20 hypothesis: tensor([148.9423, 178.9730, 169.8976, 192.0301, 136.5279]) Cost: 38.687496
Epoch:   7/ 20 hypothesis: tensor([151.1574, 181.6346, 172.4254, 194.8856, 138.5585]) Cost: 16.499043
Epoch:   8/ 20 hypothesis: tensor([152.4131, 183.1435, 173.8590, 196.5043, 139.7097]) Cost: 9.365656
Epoch:   9/ 20 hypothesis: tensor([153.1250, 183.9988, 174.6723, 197.4217, 140.3625]) Cost: 7.071114
Epoch: 

In [26]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [27]:
torch.manual_seed(1)

In [28]:
x_train= torch.FloatTensor([[1],[2],[3]])
y_train= torch.FloatTensor([[2],[4],[6]])

In [29]:
model=nn.Linear(1,1)

In [31]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [32]:
optimizer= torch.optim.SGD(model.parameters(), lr= 0.01)

In [33]:
nb_epochs= 2000
for epoch in range(nb_epochs+1):
  prediction= model(x_train)

  cost=F.mse_loss(prediction, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch %100==0:
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item()) )

Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


In [34]:
new_var= torch.FloatTensor([[4.0]])

In [35]:
pred_y= model(new_var)

In [36]:
print('훈련 후 입력이 4일 때의 예측값 :', pred_y)

훈련 후 입력이 4일 때의 예측값 : tensor([[7.9989]], grad_fn=<AddmmBackward0>)


In [38]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
torch.manual_seed(1)

In [43]:
x_train= torch.FloatTensor([[73,80,75],
                            [93,88,93],
                            [89,91,90],
                            [96,98,100],
                            [73,66,70]])
y_train= torch.FloatTensor([[152],[185],[180],[196],[142]])

In [44]:
model= nn.Linear(3,1)

In [46]:
print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119]], requires_grad=True), Parameter containing:
tensor([0.2710], requires_grad=True)]


In [47]:
optimizer=torch.optim.SGD(model.parameters(),lr=1e-5)
optimizer_test=torch.optim.SGD(model.parameters(), lr=0.01)

In [48]:
nb_epochs= 2000
for epoch in range(nb_epochs+1):
  prediction= model(x_train)

  cost= F.mse_loss(prediction, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch% 100==0:
    print('Epoch: {:4d}/ {} Cost: {:.6f}'.format(
        epoch, nb_epochs, cost.item()
    ))

Epoch:    0/ 2000 Cost: 31667.597656
Epoch:  100/ 2000 Cost: 0.225993
Epoch:  200/ 2000 Cost: 0.223911
Epoch:  300/ 2000 Cost: 0.221941
Epoch:  400/ 2000 Cost: 0.220059
Epoch:  500/ 2000 Cost: 0.218271
Epoch:  600/ 2000 Cost: 0.216575
Epoch:  700/ 2000 Cost: 0.214950
Epoch:  800/ 2000 Cost: 0.213413
Epoch:  900/ 2000 Cost: 0.211952
Epoch: 1000/ 2000 Cost: 0.210560
Epoch: 1100/ 2000 Cost: 0.209232
Epoch: 1200/ 2000 Cost: 0.207967
Epoch: 1300/ 2000 Cost: 0.206761
Epoch: 1400/ 2000 Cost: 0.205619
Epoch: 1500/ 2000 Cost: 0.204522
Epoch: 1600/ 2000 Cost: 0.203484
Epoch: 1700/ 2000 Cost: 0.202485
Epoch: 1800/ 2000 Cost: 0.201542
Epoch: 1900/ 2000 Cost: 0.200635
Epoch: 2000/ 2000 Cost: 0.199769


In [49]:
new_var= torch.FloatTensor([[73,80,75]])
pred_y= model(new_var)
print('훈련 후 입력이 73,80,75 일 때의 예측값 :', pred_y
      )

훈련 후 입력이 73,80,75 일 때의 예측값 : tensor([[151.2305]], grad_fn=<AddmmBackward0>)


In [50]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.9778, 0.4539, 0.5768]], requires_grad=True), Parameter containing:
tensor([0.2802], requires_grad=True)]


In [52]:
nb_epochs=2000
for epoch in range(nb_epochs+1):
  prediction=model(x_train)
  cost= F.mse_loss(prediction, y_train)

  optimizer_test.zero_grad()
  cost.backward()
  optimizer_test.step()
  
  if epoch%100==0:
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(epoch, nb_epochs, cost.item()))

Epoch    0/2000 Cost: 0.199762
Epoch  100/2000 Cost: nan
Epoch  200/2000 Cost: nan
Epoch  300/2000 Cost: nan
Epoch  400/2000 Cost: nan
Epoch  500/2000 Cost: nan
Epoch  600/2000 Cost: nan
Epoch  700/2000 Cost: nan
Epoch  800/2000 Cost: nan
Epoch  900/2000 Cost: nan
Epoch 1000/2000 Cost: nan
Epoch 1100/2000 Cost: nan
Epoch 1200/2000 Cost: nan
Epoch 1300/2000 Cost: nan
Epoch 1400/2000 Cost: nan
Epoch 1500/2000 Cost: nan
Epoch 1600/2000 Cost: nan
Epoch 1700/2000 Cost: nan
Epoch 1800/2000 Cost: nan
Epoch 1900/2000 Cost: nan
Epoch 2000/2000 Cost: nan


In [53]:
new_var= torch.FloatTensor([[73,80,75]])
pred_y= model(new_var)
print('훈련 후 입력이 73,80,75 일 때의 예측값 :', pred_y
      )

훈련 후 입력이 73,80,75 일 때의 예측값 : tensor([[nan]], grad_fn=<AddmmBackward0>)


In [54]:
print(list(model.parameters()))

[Parameter containing:
tensor([[nan, nan, nan]], requires_grad=True), Parameter containing:
tensor([nan], requires_grad=True)]


In [55]:
model= nn.Linear(1,1)

In [3]:
class LinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(1,1)

    def forward(self, x):
      return self.linear(x)

In [4]:
model=LinearRegressionModel()

In [5]:
model=nn.Linear(3,1)

In [6]:
class MultivariateLinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear= nn.Linear(3,1)

  def forward(self, x):
    return sefl.linear(x)

In [7]:
model= MultivariateLinearRegressionModel()

In [8]:
import torch
import torch.nn as nn
import torch.nn.functional as F
torch.manual_seed(1)

In [9]:
x_train= torch.FloatTensor([[1],[2],[3]])
y_train= torch.FloatTensor([[2],[4],[6]])

In [10]:
class LinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear=nn.Linear(1,1)

  def forward(self, x):
    return self.linear(x)
model= LinearRegressionModel()

In [11]:
optimizer= torch.optim.SGD(model.parameters(), lr=0.01)

In [12]:
nb_epochs= 2000
for epoch in range(nb_epochs+1):
  prediction= model(x_train)
  cost= F.mse_loss(prediction, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch%100==0:

    print('Epoch: {:4d}/{} Cost: {:.5f}'.format(epoch, nb_epochs, cost.item())
  )

Epoch:    0/2000 Cost: 13.10354
Epoch:  100/2000 Cost: 0.00279
Epoch:  200/2000 Cost: 0.00172
Epoch:  300/2000 Cost: 0.00107
Epoch:  400/2000 Cost: 0.00066
Epoch:  500/2000 Cost: 0.00041
Epoch:  600/2000 Cost: 0.00025
Epoch:  700/2000 Cost: 0.00016
Epoch:  800/2000 Cost: 0.00010
Epoch:  900/2000 Cost: 0.00006
Epoch: 1000/2000 Cost: 0.00004
Epoch: 1100/2000 Cost: 0.00002
Epoch: 1200/2000 Cost: 0.00001
Epoch: 1300/2000 Cost: 0.00001
Epoch: 1400/2000 Cost: 0.00001
Epoch: 1500/2000 Cost: 0.00000
Epoch: 1600/2000 Cost: 0.00000
Epoch: 1700/2000 Cost: 0.00000
Epoch: 1800/2000 Cost: 0.00000
Epoch: 1900/2000 Cost: 0.00000
Epoch: 2000/2000 Cost: 0.00000


In [13]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


In [14]:
import torch 
import torch.nn as nn
import torch.nn.functional as F
torch.manual_seed(1)

In [15]:
x_train=torch.FloatTensor([[73,80,75],
                           [93,88,93],
                           [89,91,90],
                           [96,98,100],
                           [73,66,70]])
y_train= torch.FloatTensor([[152],[185],[180],[196],[142]])

In [16]:
class MultivariateLinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear= nn.Linear(3,1)

  def forward(self, x):
    return self.linear(x)

In [17]:
model= MultivariateLinearRegressionModel()
optimizer= torch.optim.SGD(model.parameters(), lr=1e-5)

In [19]:
nb_epochs=20000
for epoch in range(nb_epochs+1):
  prediction = model(x_train)

  cost=F.mse_loss(prediction, y_train)

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch%100==0:
    print('Epoch : {:4d}/ {} Cost: {:.5f}'.format(epoch, nb_epochs, cost.item()))

Epoch :    0/ 20000 Cost: 9926.26562
Epoch :  100/ 20000 Cost: 0.22597
Epoch :  200/ 20000 Cost: 0.22390
Epoch :  300/ 20000 Cost: 0.22192
Epoch :  400/ 20000 Cost: 0.22004
Epoch :  500/ 20000 Cost: 0.21825
Epoch :  600/ 20000 Cost: 0.21655
Epoch :  700/ 20000 Cost: 0.21494
Epoch :  800/ 20000 Cost: 0.21340
Epoch :  900/ 20000 Cost: 0.21194
Epoch : 1000/ 20000 Cost: 0.21055
Epoch : 1100/ 20000 Cost: 0.20922
Epoch : 1200/ 20000 Cost: 0.20796
Epoch : 1300/ 20000 Cost: 0.20676
Epoch : 1400/ 20000 Cost: 0.20560
Epoch : 1500/ 20000 Cost: 0.20451
Epoch : 1600/ 20000 Cost: 0.20347
Epoch : 1700/ 20000 Cost: 0.20247
Epoch : 1800/ 20000 Cost: 0.20153
Epoch : 1900/ 20000 Cost: 0.20063
Epoch : 2000/ 20000 Cost: 0.19976
Epoch : 2100/ 20000 Cost: 0.19894
Epoch : 2200/ 20000 Cost: 0.19815
Epoch : 2300/ 20000 Cost: 0.19740
Epoch : 2400/ 20000 Cost: 0.19668
Epoch : 2500/ 20000 Cost: 0.19599
Epoch : 2600/ 20000 Cost: 0.19533
Epoch : 2700/ 20000 Cost: 0.19471
Epoch : 2800/ 20000 Cost: 0.19410
Epoch : 290

In [20]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.9873, 0.4919, 0.5298]], requires_grad=True), Parameter containing:
tensor([0.2900], requires_grad=True)]


In [21]:
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

In [22]:
x_train  =  torch.FloatTensor([[73,  80,  75], 
                               [93,  88,  93], 
                               [89,  91,  90], 
                               [96,  98,  100],   
                               [73,  66,  70]])  
y_train  =  torch.FloatTensor([[152],  [185],  [180],  [196],  [142]])

In [23]:
dataset=TensorDataset(x_train,y_train)

In [24]:
dataloader= DataLoader(dataset, batch_size=2, shuffle=True)

In [25]:
model=nn.Linear(3,1)
optimizer= torch.optim.SGD(model.parameters(), lr=1e-5)

In [29]:
nb_epochs=20
for epoch in range(nb_epochs+1):
  for batch_idx, samples in enumerate(dataloader):
    print(batch_idx)
    print(samples)
    x_train, y_train = samples

    prediction=model(x_train)
    cost= F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch: {:4d}/{} Batch:{}/{} Cost: {:.5f}'.format(
        epoch, nb_epochs, batch_idx+1, len(dataloader), cost.item()
    ))

0
[tensor([[93., 88., 93.],
        [73., 80., 75.]]), tensor([[185.],
        [152.]])]
Epoch:    0/20 Batch:1/3 Cost: 13.74888
1
[tensor([[ 73.,  66.,  70.],
        [ 96.,  98., 100.]]), tensor([[142.],
        [196.]])]
Epoch:    0/20 Batch:2/3 Cost: 13.72004
2
[tensor([[89., 91., 90.]]), tensor([[180.]])]
Epoch:    0/20 Batch:3/3 Cost: 4.19145
0
[tensor([[73., 66., 70.],
        [93., 88., 93.]]), tensor([[142.],
        [185.]])]
Epoch:    1/20 Batch:1/3 Cost: 23.27919
1
[tensor([[ 89.,  91.,  90.],
        [ 96.,  98., 100.]]), tensor([[180.],
        [196.]])]
Epoch:    1/20 Batch:2/3 Cost: 10.13991
2
[tensor([[73., 80., 75.]]), tensor([[152.]])]
Epoch:    1/20 Batch:3/3 Cost: 12.42472
0
[tensor([[93., 88., 93.],
        [89., 91., 90.]]), tensor([[185.],
        [180.]])]
Epoch:    2/20 Batch:1/3 Cost: 13.76364
1
[tensor([[ 96.,  98., 100.],
        [ 73.,  80.,  75.]]), tensor([[196.],
        [152.]])]
Epoch:    2/20 Batch:2/3 Cost: 6.61229
2
[tensor([[73., 66., 70.]]), tens

In [30]:
new_var= torch.FloatTensor([[73,80,75]])
pred_y= model(new_var)
print('훈련 후 입력이 73,80,75일 때의 예측값:', pred_y)

훈련 후 입력이 73,80,75일 때의 예측값: tensor([[155.3497]], grad_fn=<AddmmBackward0>)
