<a href="https://colab.research.google.com/github/JamesLeeeeeee/torchbase/blob/master/torchbase_20220202.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import torch.nn.functional as F
torch.manual_seed(1)

In [3]:
z= torch.FloatTensor([1,2,3])

In [4]:
hypothesis= F.softmax(z, dim=0)
print(hypothesis)

tensor([0.0900, 0.2447, 0.6652])


In [5]:
hypothesis.sum()

tensor(1.)

In [6]:
 z= torch.rand(3,5, requires_grad=True)

In [7]:
hypothesis= F.softmax(z, dim=1)
print(hypothesis)

tensor([[0.2645, 0.1639, 0.1855, 0.2585, 0.1277],
        [0.2430, 0.1624, 0.2322, 0.1930, 0.1694],
        [0.2226, 0.1986, 0.2326, 0.1594, 0.1868]], grad_fn=<SoftmaxBackward0>)


In [8]:
hypothesis.sum()

tensor(3.0000, grad_fn=<SumBackward0>)

In [9]:
y= torch.randint(5, (3,)).long()
print(y)

tensor([0, 2, 1])


In [10]:
y_one_hot= torch.zeros_like(hypothesis)
y_one_hot.scatter_(1,y.unsqueeze(1),1)

tensor([[1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 0.]])

In [11]:
print(y.unsqueeze(1))

tensor([[0],
        [2],
        [1]])


In [12]:
cost=(y_one_hot* -torch.log(hypothesis)).sum(dim=1).mean()
print(cost)

tensor(1.4689, grad_fn=<MeanBackward0>)


In [13]:
F.log_softmax(z,dim=1)

tensor([[-1.3301, -1.8084, -1.6846, -1.3530, -2.0584],
        [-1.4147, -1.8174, -1.4602, -1.6450, -1.7758],
        [-1.5025, -1.6165, -1.4586, -1.8360, -1.6776]],
       grad_fn=<LogSoftmaxBackward0>)

In [14]:
F.nll_loss(F.log_softmax(z,dim=1),y)

tensor(1.4689, grad_fn=<NllLossBackward0>)

In [15]:
F.cross_entropy(z,y)

tensor(1.4689, grad_fn=<NllLossBackward0>)

In [16]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
torch.manual_seed(1)

In [17]:
x_train = [[1, 2, 1, 1],
           [2, 1, 3, 2],
           [3, 1, 3, 4],
           [4, 1, 5, 5],
           [1, 7, 5, 5],
           [1, 2, 5, 6],
           [1, 6, 6, 6],
           [1, 7, 7, 7]]
y_train = [2, 2, 2, 1, 1, 1, 0, 0]
x_train = torch.FloatTensor(x_train)
y_train = torch.LongTensor(y_train)

In [18]:
print(x_train.shape)
print(y_train.shape)

torch.Size([8, 4])
torch.Size([8])


In [19]:
y_one_hot=torch.zeros(8,3)
y_one_hot.scatter(1,y_train.unsqueeze(1),1)
print(y_one_hot.shape)

torch.Size([8, 3])


In [ ]:
W=torch.zeros((4,3), requires_grad=True)
b=torch.zeros.(1, requires)