<a href="https://colab.research.google.com/github/JamesLeeeeeee/torchbase/blob/master/torchbase_20220103.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [4]:
torch.manual_seed(1)

In [5]:
x_train= torch.FloatTensor([[1],[2],[3]])
y_train= torch.FloatTensor([[2],[4],[6]])

In [6]:
print(x_train)
print(x_train.shape)
print(y_train)
print(y_train.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])
tensor([[2.],
        [4.],
        [6.]])
torch.Size([3, 1])


In [7]:
W=torch.zeros(1, requires_grad=True)
print(W)

tensor([0.], requires_grad=True)


In [8]:
b= torch.zeros(1, requires_grad=True)
print(b)

tensor([0.], requires_grad=True)


In [9]:
hypothesis= x_train*W+b
print(hypothesis)

tensor([[0.],
        [0.],
        [0.]], grad_fn=<AddBackward0>)


In [10]:
cost= torch.mean((hypothesis - y_train)**2)
print(cost)

tensor(18.6667, grad_fn=<MeanBackward0>)


In [11]:
optimizer= optim.SGD([W, b], lr=0.01)

In [12]:
optimizer.zero_grad() #gradient 0으로 초기화

cost.backward()  # 비용함수를 미분해서 가중치와 편향 계산
optimizer.step() #W와 b에서 리턴되는 변수들의 기울기에 lr(learningrate를 곱해 기울기에서 빼줌)


In [19]:
x_train= torch.FloatTensor([[1],[2],[3]])
y_train= torch.FloatTensor([[2],[4],[6]])
W=torch.zeros(1,requires_grad=True)
b= torch.zeros(1, requires_grad=True)
optimizer= optim.SGD([W,b], lr=0.01)
nb_epochs = 1999 #경사하강법 반복 수

In [20]:
for epoch in range(nb_epochs+2):
  hypothesis= x_train*W+b #H(x)계산< 가설 수립
  cost= torch.mean((hypothesis - y_train)**2) #평균제곱오차
  #코스트로 H(x)개선
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()
  if epoch%100==0:
    print('Epoch {:4d}/{} W: {:.3f} b: {:.3f} Cost: {:.6f}'.format(epoch, nb_epochs, 
                                                         W.item(), b.item(),
                                                         cost.item()))

Epoch    0/1999 W: 0.187 b: 0.080 Cost: 18.666666
Epoch  100/1999 W: 1.746 b: 0.578 Cost: 0.048171
Epoch  200/1999 W: 1.800 b: 0.454 Cost: 0.029767
Epoch  300/1999 W: 1.843 b: 0.357 Cost: 0.018394
Epoch  400/1999 W: 1.876 b: 0.281 Cost: 0.011366
Epoch  500/1999 W: 1.903 b: 0.221 Cost: 0.007024
Epoch  600/1999 W: 1.924 b: 0.174 Cost: 0.004340
Epoch  700/1999 W: 1.940 b: 0.136 Cost: 0.002682
Epoch  800/1999 W: 1.953 b: 0.107 Cost: 0.001657
Epoch  900/1999 W: 1.963 b: 0.084 Cost: 0.001024
Epoch 1000/1999 W: 1.971 b: 0.066 Cost: 0.000633
Epoch 1100/1999 W: 1.977 b: 0.052 Cost: 0.000391
Epoch 1200/1999 W: 1.982 b: 0.041 Cost: 0.000242
Epoch 1300/1999 W: 1.986 b: 0.032 Cost: 0.000149
Epoch 1400/1999 W: 1.989 b: 0.025 Cost: 0.000092
Epoch 1500/1999 W: 1.991 b: 0.020 Cost: 0.000057
Epoch 1600/1999 W: 1.993 b: 0.016 Cost: 0.000035
Epoch 1700/1999 W: 1.995 b: 0.012 Cost: 0.000022
Epoch 1800/1999 W: 1.996 b: 0.010 Cost: 0.000013
Epoch 1900/1999 W: 1.997 b: 0.008 Cost: 0.000008
Epoch 2000/1999 W: 

In [21]:
w= torch.tensor(2.0, requires_grad=True)
nb_epochs= 20
for epoch in range(nb_epochs+1):
  z= 2*w
  z.backward()
  print('수식을 w로 미분한 값 : {}'.format(w.grad))

수식을 w로 미분한 값 : 2.0
수식을 w로 미분한 값 : 4.0
수식을 w로 미분한 값 : 6.0
수식을 w로 미분한 값 : 8.0
수식을 w로 미분한 값 : 10.0
수식을 w로 미분한 값 : 12.0
수식을 w로 미분한 값 : 14.0
수식을 w로 미분한 값 : 16.0
수식을 w로 미분한 값 : 18.0
수식을 w로 미분한 값 : 20.0
수식을 w로 미분한 값 : 22.0
수식을 w로 미분한 값 : 24.0
수식을 w로 미분한 값 : 26.0
수식을 w로 미분한 값 : 28.0
수식을 w로 미분한 값 : 30.0
수식을 w로 미분한 값 : 32.0
수식을 w로 미분한 값 : 34.0
수식을 w로 미분한 값 : 36.0
수식을 w로 미분한 값 : 38.0
수식을 w로 미분한 값 : 40.0
수식을 w로 미분한 값 : 42.0
